from django.db import models
from hashlib import sha256

# Create your models here.
class Link(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=255)
    collect_extended_data = models.BooleanField(default=True)
    short_id = models.CharField(max_length=6, unique=True)
    destination = models.URLField()

    def __str__(self):
        return "{} ({})".format(self.short_id, self.destination)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("link-detail", kwargs={"pk": self.pk})

    def get_delete_url(self):
        from django.urls import reverse

        return reverse("delete-link", kwargs={"pk": self.pk})

    def get_redirect_url(self):
        from django.urls import reverse

        return reverse("redirect", kwargs={"short_id": self.short_id})


class Visit(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    # Core information from the request
    link = models.ForeignKey(Link, on_delete=models.CASCADE)
    ip = models.CharField(max_length=45)
    user_agent = models.CharField(max_length=4000, null=True)
    language = models.CharField(max_length=10, null=True)
    referrer = models.CharField(max_length=1000, null=True)
    # From user agent
    device_brand = models.CharField(max_length=255, null=True)
    device_family = models.CharField(max_length=255, null=True)
    device_model = models.CharField(max_length=255, null=True)
    os_family = models.CharField(max_length=255, null=True)
    os_major = models.CharField(max_length=255, null=True)
    os_minor = models.CharField(max_length=255, null=True)
    os_patch = models.CharField(max_length=255, null=True)
    browser_family = models.CharField(max_length=255, null=True)
    browser_major = models.CharField(max_length=255, null=True)
    browser_minor = models.CharField(max_length=255, null=True)
    browser_patch = models.CharField(max_length=255, null=True)

    # Generated by us
    is_bot = models.BooleanField(default=False)
    fingerprint = models.CharField(max_length=40)

    # Details from ipinfo.io
    city = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=2, null=True)
    hostname = models.CharField(max_length=255, null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    # Details from JS fingerprint
    webdriver = models.BooleanField(null=True)
    color_depth = models.IntegerField(null=True)
    pixel_ratio = models.FloatField(null=True)
    hardware_concurrency = models.IntegerField(null=True)
    screen_x = models.IntegerField(null=True)
    screen_y = models.IntegerField(null=True)
    available_screen_x = models.IntegerField(null=True)
    available_screen_y = models.IntegerField(null=True)
    timezone = models.CharField(max_length=255, null=True)
    session_storage = models.BooleanField(null=True)
    local_storage = models.BooleanField(null=True)
    indexed_db = models.BooleanField(null=True)
    add_behavior = models.BooleanField(null=True)
    open_database = models.BooleanField(null=True)
    platform = models.CharField(max_length=255, null=True)
    webgl_vendor_and_renderer = models.CharField(max_length=255, null=True)
    touch_support = models.BooleanField(null=True)

    def save(self, *args, **kwargs):
        fingerprint_fields = [f for f in [
            self.device_brand,
            self.device_family,
            self.device_model,
            self.os_family,
            self.os_major,
            self.os_minor,
            self.os_patch,
            self.browser_family,
            # TODO: browser_major?
            self.language,
            self.webdriver,
            self.color_depth,
            self.pixel_ratio,
            self.hardware_concurrency,
            self.screen_x,
            self.screen_y,
            self.available_screen_x,
            self.available_screen_y,
            self.timezone,
            self.session_storage,
            self.local_storage,
            self.indexed_db,
            self.add_behavior,
            self.open_database,
            self.platform,
            self.webgl_vendor_and_renderer,
            self.touch_support,
        ] if f is not None]
        self.fingerprint = sha256(bytes("".join([str(f) for f in fingerprint_fields]), encoding="utf8")).hexdigest()
        super().save(*args, **kwargs)  # Call the "real" save() method.

    class Meta:
        indexes = [models.Index(fields=["fingerprint"])]
