from django.db import models
from hashlib import sha1

# Create your models here.
class Link(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=255)
    short_id = models.CharField(max_length=6, unique=True)
    destination = models.URLField()

    def __str__(self):
        return "{} ({})".format(self.short_id, self.destination)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("link-detail", kwargs={"pk": self.pk})

    def get_redirect_url(self):
        from django.urls import reverse
        return reverse('redirect', kwargs={'short_id': self.short_id})


class Visit(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    link = models.ForeignKey(Link, on_delete=models.CASCADE)
    user_agent = models.CharField(max_length=4000)
    ip = models.CharField(max_length=45)

    # Generated by us
    is_bot = models.BooleanField(default=False)
    fingerprint = models.CharField(max_length=40)

    # Details from ipinfo.io
    city = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=2, null=True)
    hostname = models.CharField(max_length=255, null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    def save(self, *args, **kwargs):
        fingerprint_fields = bytes(''.join([self.user_agent, self.ip]), encoding='utf8')
        self.fingerprint = sha1(fingerprint_fields).hexdigest()
        print(self.fingerprint)
        super().save(*args, **kwargs)  # Call the "real" save() method.

    class Meta:
        indexes = [
            models.Index(fields=['fingerprint'])
        ]
