# Generated by Django 3.0.5 on 2020-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="collect_extended_data",
            field=models.BooleanField(default=False),
        ),
    ]
