# Generated by Django 3.0.5 on 2020-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='referrer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
