# Generated by Django 3.0.5 on 2020-05-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_visit_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="language",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
