# Generated by Django 3.0.5 on 2020-05-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_link_collect_extended_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="add_behavior",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="available_screen_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="available_screen_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="color_depth",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="hardware_concurrency",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visit", name="indexed_db", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="language",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="local_storage",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="open_database",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit", name="pixel_ratio", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="platform",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="visit", name="screen_x", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visit", name="screen_y", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="session_storage",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="timezone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="touch_support",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit", name="webdriver", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="webgl_vendor_and_renderer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="user_agent",
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
