# Generated by Django 3.0.5 on 2020-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20200506_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='fingerprint',
            field=models.CharField(max_length=255),
        ),
    ]
