# Generated by Django 4.2.3 on 2023-07-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20200506_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='add_behavior',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='available_screen_x',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='available_screen_y',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='color_depth',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='hardware_concurrency',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='indexed_db',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='local_storage',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='open_database',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='pixel_ratio',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='session_storage',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='touch_support',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='webdriver',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='webgl_vendor_and_renderer',
        ),
        migrations.AddField(
            model_name='visit',
            name='fingerprint_fields',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_family',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_major',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_minor',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_patch',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='city',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device_brand',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device_family',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device_model',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='fingerprint',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hostname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os_family',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os_major',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os_minor',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os_patch',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
