# Generated by Django 4.2.3 on 2023-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_remove_visit_add_behavior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='fingerprint_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
